Movie like
djuka88/movie-app-backend pull request #4
Opened 2022-06-02 06:14 UTC by djuka88

2022-06-02 08:20 UTC, ivns1993 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->increments('id');
u ovom slucaju ok ako si ti rollbackovao sve, ali inace ni slucajno ne menjamo stare migracije koje je neko vec runovao, ako ih niko drugi jos nije runovao onda i ok (dok rollbackujemo), a ovako ako nam treba neka izmena pravimo novu migraciju sa tom izmenom. Posto migracije koje su vec pokrenute, nece se opet pokrenuti ako ih izmenimo i samim tim ce neko ostati bez potrebnih izmena

2022-06-02 08:20 UTC, ivns1993 commented on app/Providers/AppServiceProvider.php
> -        DB::listen(function($query) {
ovde gore je ostao import za DB i Log koji ne treba da ostanu u PR (a ostali su u proslom koji nisam stigla opet da pogledam pre merga)

2022-06-02 08:20 UTC, ivns1993 commented on app/Models/Movie.php
> +    public function scopeUserReaction($query)
nice :)

2022-06-02 08:20 UTC, ivns1993 commented on app/Models/Movie.php
> +    public function scopeGenresFilter($query, $genresFilter)
zar ovo nisu stare promene? nije mi jasno sto ih vidimo ovde u diffu 🤔

2022-06-02 08:20 UTC, ivns1993 commented on app/Http/Requests/ReactRequest.php
> +        ];
odlicno

2022-06-02 08:20 UTC, ivns1993 commented on app/Http/Controllers/MovieController.php
> +        if($reactionFromDb->like == $userReaction){
if ($reactionFromDb->like == $userReaction) {
            $reactionFromDb->delete();
        } else {
            $reactionFromDb->like = $userReaction;
            $reactionFromDb->save();
        }

2022-06-02 08:20 UTC, ivns1993 commented on app/Http/Controllers/MovieController.php
> +        $movies = Movie::
Movie:: kad ostane sam u redu strasno izgleda, nek ostane u ovom redu searchFilter :D

2022-06-02 08:20 UTC, ivns1993 commented on app/Http/Controllers/MovieController.php
> +            ->paginate(10);
bravo, bas lepo sve uklopljeno

2022-06-03 06:42 UTC, djuka88 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->increments('id');
aha okej

2022-06-03 09:44 UTC, ivns1993 requested changes

2022-06-03 09:44 UTC, ivns1993 commented on app/Http/Controllers/MovieController.php
> +            }
if (count($movie->reactions) > 0) {
                $newValue = $movie->reactions[0]->like;
                unset($movie->reactions);
                $movie->reaction = $newValue;
            } else {
                unset($movie->reactions);
            }


moramo malo vise obratiti paznju na formatiranje - kad se drzimo nekih standarda u formatiranju onda znamo tacno sta gde da ocekujemo u kodu i postane mnogo preglednije i brze ga citamo

2022-06-03 09:44 UTC, ivns1993 commented on app/Http/Controllers/MovieController.php
> +        if($reactionFromDb->like == $userReaction){
razmaci i dalje fale ovde

2022-06-03 10:30 UTC, djuka88 commented on app/Http/Controllers/MovieController.php
> +            }
ah.. ma pre sam uvek pisao else u novoj liniji.. pa dok se naviknem

2022-07-26 07:29 UTC, closed without merging